version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Desafio-NEPEN/Dockerfile
    container_name: nepen-api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=postgres;Database=nepen-dev;Username=postgres;Password=admin
      - Redis__Connection=redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs:rw

  postgres:
    image: postgres:15
    container_name: nepen-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nepen-dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: nepen-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
