// <auto-generated />
using System;
using Desafio_NEPEN.Com.Nepen.Infra.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Desafio_NEPEN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Desafio_NEPEN.Com.Nepen.Core.Entities.Leitura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Corrente")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EnergiaAtivaDireta")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EnergiaAtivaReversa")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FatorPotencia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Frequencia")
                        .HasColumnType("numeric");

                    b.Property<string>("MedidorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PotenciaAtiva")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PotenciaReativa")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Tensao")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MedidorId");

                    b.ToTable("Leituras");
                });

            modelBuilder.Entity("Desafio_NEPEN.Com.Nepen.Core.Entities.Medidor", b =>
                {
                    b.Property<string>("MedidorId")
                        .HasColumnType("text");

                    b.HasKey("MedidorId");

                    b.ToTable("Medidores");
                });

            modelBuilder.Entity("Desafio_NEPEN.Com.Nepen.Core.Entities.Leitura", b =>
                {
                    b.HasOne("Desafio_NEPEN.Com.Nepen.Core.Entities.Medidor", "Medidor")
                        .WithMany("Leituras")
                        .HasForeignKey("MedidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medidor");
                });

            modelBuilder.Entity("Desafio_NEPEN.Com.Nepen.Core.Entities.Medidor", b =>
                {
                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
